# Generated by Django 3.0.3 on 2020-04-17 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20200416_2343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='facilties',
            new_name='facilities',
        ),
    ]
