# Generated by Django 3.0.3 on 2020-04-16 22:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0004_auto_20200416_2343"),
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review", old_name="check_ine", new_name="check_in",
        ),
        migrations.AddField(
            model_name="review",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rooms.Room"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="review", name="review", field=models.TextField(),
        ),
    ]
